services:
  server:
    container_name: we-code-server
    build:
      context: ./server
      dockerfile: Dockerfile
      target: runner
    volumes:
      - ./server:/app
      - /build/node_modules
    networks:
      - We-Code
    ports:
      - "5000:5000"

  client:
    container_name: we-code-client
    build:
      context: ./client
      dockerfile: Dockerfile
      target: runner
    volumes:
      - ./client:/app
      - /build/node_modules
    networks:
      - We-Code
    ports:
      - "5173:5173"
    depends_on:
      - server

networks:
  We-Code:
    driver: bridge
